# coding: utf-8

"""
    Energy Scoring

    Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Address(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'city': 'str',
        'country_iso_code': 'str',
        'zip_code': 'str',
        'state_code': 'str',
        'timezone': 'str',
        'coordinates': 'Coordinates'
    }

    attribute_map = {
        'address': 'address',
        'city': 'city',
        'country_iso_code': 'countryIsoCode',
        'zip_code': 'zipCode',
        'state_code': 'stateCode',
        'timezone': 'timezone',
        'coordinates': 'coordinates'
    }

    def __init__(self, address=None, city=None, country_iso_code=None, zip_code=None, state_code=None, timezone=None, coordinates=None):  # noqa: E501
        """Address - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._city = None
        self._country_iso_code = None
        self._zip_code = None
        self._state_code = None
        self._timezone = None
        self._coordinates = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if city is not None:
            self.city = city
        if country_iso_code is not None:
            self.country_iso_code = country_iso_code
        if zip_code is not None:
            self.zip_code = zip_code
        if state_code is not None:
            self.state_code = state_code
        if timezone is not None:
            self.timezone = timezone
        if coordinates is not None:
            self.coordinates = coordinates

    @property
    def address(self):
        """Gets the address of this Address.  # noqa: E501


        :return: The address of this Address.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this Address.


        :param address: The address of this Address.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def city(self):
        """Gets the city of this Address.  # noqa: E501


        :return: The city of this Address.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this Address.


        :param city: The city of this Address.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def country_iso_code(self):
        """Gets the country_iso_code of this Address.  # noqa: E501


        :return: The country_iso_code of this Address.  # noqa: E501
        :rtype: str
        """
        return self._country_iso_code

    @country_iso_code.setter
    def country_iso_code(self, country_iso_code):
        """Sets the country_iso_code of this Address.


        :param country_iso_code: The country_iso_code of this Address.  # noqa: E501
        :type: str
        """

        self._country_iso_code = country_iso_code

    @property
    def zip_code(self):
        """Gets the zip_code of this Address.  # noqa: E501


        :return: The zip_code of this Address.  # noqa: E501
        :rtype: str
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code):
        """Sets the zip_code of this Address.


        :param zip_code: The zip_code of this Address.  # noqa: E501
        :type: str
        """

        self._zip_code = zip_code

    @property
    def state_code(self):
        """Gets the state_code of this Address.  # noqa: E501


        :return: The state_code of this Address.  # noqa: E501
        :rtype: str
        """
        return self._state_code

    @state_code.setter
    def state_code(self, state_code):
        """Sets the state_code of this Address.


        :param state_code: The state_code of this Address.  # noqa: E501
        :type: str
        """

        self._state_code = state_code

    @property
    def timezone(self):
        """Gets the timezone of this Address.  # noqa: E501


        :return: The timezone of this Address.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this Address.


        :param timezone: The timezone of this Address.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    @property
    def coordinates(self):
        """Gets the coordinates of this Address.  # noqa: E501


        :return: The coordinates of this Address.  # noqa: E501
        :rtype: Coordinates
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates):
        """Sets the coordinates of this Address.


        :param coordinates: The coordinates of this Address.  # noqa: E501
        :type: Coordinates
        """

        self._coordinates = coordinates

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Address, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Address):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
