# coding: utf-8

"""
    Energy Scoring

    Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CertificationProvider(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'leed_id': 'int',
        'leed_name': 'str'
    }

    attribute_map = {
        'leed_id': 'leedId',
        'leed_name': 'leedName'
    }

    def __init__(self, leed_id=None, leed_name=None):  # noqa: E501
        """CertificationProvider - a model defined in Swagger"""  # noqa: E501
        self._leed_id = None
        self._leed_name = None
        self.discriminator = None
        self.leed_id = leed_id
        self.leed_name = leed_name

    @property
    def leed_id(self):
        """Gets the leed_id of this CertificationProvider.  # noqa: E501


        :return: The leed_id of this CertificationProvider.  # noqa: E501
        :rtype: int
        """
        return self._leed_id

    @leed_id.setter
    def leed_id(self, leed_id):
        """Sets the leed_id of this CertificationProvider.


        :param leed_id: The leed_id of this CertificationProvider.  # noqa: E501
        :type: int
        """
        if leed_id is None:
            raise ValueError("Invalid value for `leed_id`, must not be `None`")  # noqa: E501

        self._leed_id = leed_id

    @property
    def leed_name(self):
        """Gets the leed_name of this CertificationProvider.  # noqa: E501


        :return: The leed_name of this CertificationProvider.  # noqa: E501
        :rtype: str
        """
        return self._leed_name

    @leed_name.setter
    def leed_name(self, leed_name):
        """Sets the leed_name of this CertificationProvider.


        :param leed_name: The leed_name of this CertificationProvider.  # noqa: E501
        :type: str
        """
        if leed_name is None:
            raise ValueError("Invalid value for `leed_name`, must not be `None`")  # noqa: E501

        self._leed_name = leed_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CertificationProvider, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CertificationProvider):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
