# coding: utf-8

"""
    Energy Scoring

    Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Error(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'title': 'str',
        'status': 'float',
        'instance': 'str',
        'detail': 'str',
        'debugging': 'str',
        'invalid_params': 'list[ErrorInvalidparams]'
    }

    attribute_map = {
        'type': 'type',
        'title': 'title',
        'status': 'status',
        'instance': 'instance',
        'detail': 'detail',
        'debugging': 'debugging',
        'invalid_params': 'invalid-params'
    }

    def __init__(self, type=None, title=None, status=None, instance=None, detail=None, debugging=None, invalid_params=None):  # noqa: E501
        """Error - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._title = None
        self._status = None
        self._instance = None
        self._detail = None
        self._debugging = None
        self._invalid_params = None
        self.discriminator = None
        self.type = type
        if title is not None:
            self.title = title
        if status is not None:
            self.status = status
        if instance is not None:
            self.instance = instance
        if detail is not None:
            self.detail = detail
        if debugging is not None:
            self.debugging = debugging
        if invalid_params is not None:
            self.invalid_params = invalid_params

    @property
    def type(self):
        """Gets the type of this Error.  # noqa: E501

        A URI reference [RFC3986] that identifies the problem type.  # noqa: E501

        :return: The type of this Error.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Error.

        A URI reference [RFC3986] that identifies the problem type.  # noqa: E501

        :param type: The type of this Error.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def title(self):
        """Gets the title of this Error.  # noqa: E501

        A short, human-readable summary of the problem type.  # noqa: E501

        :return: The title of this Error.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Error.

        A short, human-readable summary of the problem type.  # noqa: E501

        :param title: The title of this Error.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def status(self):
        """Gets the status of this Error.  # noqa: E501

        The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.  # noqa: E501

        :return: The status of this Error.  # noqa: E501
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Error.

        The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.  # noqa: E501

        :param status: The status of this Error.  # noqa: E501
        :type: float
        """

        self._status = status

    @property
    def instance(self):
        """Gets the instance of this Error.  # noqa: E501

        A URI reference that identifies the specific occurrence of the problem.  # noqa: E501

        :return: The instance of this Error.  # noqa: E501
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this Error.

        A URI reference that identifies the specific occurrence of the problem.  # noqa: E501

        :param instance: The instance of this Error.  # noqa: E501
        :type: str
        """

        self._instance = instance

    @property
    def detail(self):
        """Gets the detail of this Error.  # noqa: E501

        A human-readable explanation specific to this occurrence of the problem.  # noqa: E501

        :return: The detail of this Error.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this Error.

        A human-readable explanation specific to this occurrence of the problem.  # noqa: E501

        :param detail: The detail of this Error.  # noqa: E501
        :type: str
        """

        self._detail = detail

    @property
    def debugging(self):
        """Gets the debugging of this Error.  # noqa: E501

        Debugging information for DEV and QA environments.  # noqa: E501

        :return: The debugging of this Error.  # noqa: E501
        :rtype: str
        """
        return self._debugging

    @debugging.setter
    def debugging(self, debugging):
        """Sets the debugging of this Error.

        Debugging information for DEV and QA environments.  # noqa: E501

        :param debugging: The debugging of this Error.  # noqa: E501
        :type: str
        """

        self._debugging = debugging

    @property
    def invalid_params(self):
        """Gets the invalid_params of this Error.  # noqa: E501

        An array of validation errors.  # noqa: E501

        :return: The invalid_params of this Error.  # noqa: E501
        :rtype: list[ErrorInvalidparams]
        """
        return self._invalid_params

    @invalid_params.setter
    def invalid_params(self, invalid_params):
        """Sets the invalid_params of this Error.

        An array of validation errors.  # noqa: E501

        :param invalid_params: The invalid_params of this Error.  # noqa: E501
        :type: list[ErrorInvalidparams]
        """

        self._invalid_params = invalid_params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Error, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Error):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
