# coding: utf-8

"""
    Energy Scoring

    Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SiteMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gross_area': 'int',
        'building_occupants': 'int',
        'days_per_week_with_visitors': 'int',
        'number_of_visitors_per_day': 'int',
        'visit_duration': 'float',
        'weekly_operating_hours': 'int'
    }

    attribute_map = {
        'gross_area': 'grossArea',
        'building_occupants': 'buildingOccupants',
        'days_per_week_with_visitors': 'daysPerWeekWithVisitors',
        'number_of_visitors_per_day': 'numberOfVisitorsPerDay',
        'visit_duration': 'visitDuration',
        'weekly_operating_hours': 'weeklyOperatingHours'
    }

    def __init__(self, gross_area=None, building_occupants=None, days_per_week_with_visitors=None, number_of_visitors_per_day=None, visit_duration=None, weekly_operating_hours=None):  # noqa: E501
        """SiteMetadata - a model defined in Swagger"""  # noqa: E501
        self._gross_area = None
        self._building_occupants = None
        self._days_per_week_with_visitors = None
        self._number_of_visitors_per_day = None
        self._visit_duration = None
        self._weekly_operating_hours = None
        self.discriminator = None
        if gross_area is not None:
            self.gross_area = gross_area
        if building_occupants is not None:
            self.building_occupants = building_occupants
        if days_per_week_with_visitors is not None:
            self.days_per_week_with_visitors = days_per_week_with_visitors
        if number_of_visitors_per_day is not None:
            self.number_of_visitors_per_day = number_of_visitors_per_day
        if visit_duration is not None:
            self.visit_duration = visit_duration
        if weekly_operating_hours is not None:
            self.weekly_operating_hours = weekly_operating_hours

    @property
    def gross_area(self):
        """Gets the gross_area of this SiteMetadata.  # noqa: E501


        :return: The gross_area of this SiteMetadata.  # noqa: E501
        :rtype: int
        """
        return self._gross_area

    @gross_area.setter
    def gross_area(self, gross_area):
        """Sets the gross_area of this SiteMetadata.


        :param gross_area: The gross_area of this SiteMetadata.  # noqa: E501
        :type: int
        """

        self._gross_area = gross_area

    @property
    def building_occupants(self):
        """Gets the building_occupants of this SiteMetadata.  # noqa: E501


        :return: The building_occupants of this SiteMetadata.  # noqa: E501
        :rtype: int
        """
        return self._building_occupants

    @building_occupants.setter
    def building_occupants(self, building_occupants):
        """Sets the building_occupants of this SiteMetadata.


        :param building_occupants: The building_occupants of this SiteMetadata.  # noqa: E501
        :type: int
        """

        self._building_occupants = building_occupants

    @property
    def days_per_week_with_visitors(self):
        """Gets the days_per_week_with_visitors of this SiteMetadata.  # noqa: E501


        :return: The days_per_week_with_visitors of this SiteMetadata.  # noqa: E501
        :rtype: int
        """
        return self._days_per_week_with_visitors

    @days_per_week_with_visitors.setter
    def days_per_week_with_visitors(self, days_per_week_with_visitors):
        """Sets the days_per_week_with_visitors of this SiteMetadata.


        :param days_per_week_with_visitors: The days_per_week_with_visitors of this SiteMetadata.  # noqa: E501
        :type: int
        """

        self._days_per_week_with_visitors = days_per_week_with_visitors

    @property
    def number_of_visitors_per_day(self):
        """Gets the number_of_visitors_per_day of this SiteMetadata.  # noqa: E501


        :return: The number_of_visitors_per_day of this SiteMetadata.  # noqa: E501
        :rtype: int
        """
        return self._number_of_visitors_per_day

    @number_of_visitors_per_day.setter
    def number_of_visitors_per_day(self, number_of_visitors_per_day):
        """Sets the number_of_visitors_per_day of this SiteMetadata.


        :param number_of_visitors_per_day: The number_of_visitors_per_day of this SiteMetadata.  # noqa: E501
        :type: int
        """

        self._number_of_visitors_per_day = number_of_visitors_per_day

    @property
    def visit_duration(self):
        """Gets the visit_duration of this SiteMetadata.  # noqa: E501


        :return: The visit_duration of this SiteMetadata.  # noqa: E501
        :rtype: float
        """
        return self._visit_duration

    @visit_duration.setter
    def visit_duration(self, visit_duration):
        """Sets the visit_duration of this SiteMetadata.


        :param visit_duration: The visit_duration of this SiteMetadata.  # noqa: E501
        :type: float
        """

        self._visit_duration = visit_duration

    @property
    def weekly_operating_hours(self):
        """Gets the weekly_operating_hours of this SiteMetadata.  # noqa: E501


        :return: The weekly_operating_hours of this SiteMetadata.  # noqa: E501
        :rtype: int
        """
        return self._weekly_operating_hours

    @weekly_operating_hours.setter
    def weekly_operating_hours(self, weekly_operating_hours):
        """Sets the weekly_operating_hours of this SiteMetadata.


        :param weekly_operating_hours: The weekly_operating_hours of this SiteMetadata.  # noqa: E501
        :type: int
        """

        self._weekly_operating_hours = weekly_operating_hours

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SiteMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SiteMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
