/*
 * Energy Scoring
 * Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ErrorInvalidparams;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * Error occurred while handling the request (based on rfc7807)
 */
@Schema(description = "Error occurred while handling the request (based on rfc7807)")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-09-22T12:58:44.587342+02:00[Europe/Madrid]")
public class Error {
  @SerializedName("type")
  private String type = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("status")
  private BigDecimal status = null;

  @SerializedName("instance")
  private String instance = null;

  @SerializedName("detail")
  private String detail = null;

  @SerializedName("debugging")
  private String debugging = null;

  @SerializedName("invalid-params")
  private List<ErrorInvalidparams> invalidParams = null;

  public Error type(String type) {
    this.type = type;
    return this;
  }

   /**
   * A URI reference [RFC3986] that identifies the problem type.
   * @return type
  **/
  @Schema(required = true, description = "A URI reference [RFC3986] that identifies the problem type.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Error title(String title) {
    this.title = title;
    return this;
  }

   /**
   * A short, human-readable summary of the problem type.
   * @return title
  **/
  @Schema(description = "A short, human-readable summary of the problem type.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Error status(BigDecimal status) {
    this.status = status;
    return this;
  }

   /**
   * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
   * @return status
  **/
  @Schema(description = "The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.")
  public BigDecimal getStatus() {
    return status;
  }

  public void setStatus(BigDecimal status) {
    this.status = status;
  }

  public Error instance(String instance) {
    this.instance = instance;
    return this;
  }

   /**
   * A URI reference that identifies the specific occurrence of the problem.
   * @return instance
  **/
  @Schema(description = "A URI reference that identifies the specific occurrence of the problem.")
  public String getInstance() {
    return instance;
  }

  public void setInstance(String instance) {
    this.instance = instance;
  }

  public Error detail(String detail) {
    this.detail = detail;
    return this;
  }

   /**
   * A human-readable explanation specific to this occurrence of the problem.
   * @return detail
  **/
  @Schema(description = "A human-readable explanation specific to this occurrence of the problem.")
  public String getDetail() {
    return detail;
  }

  public void setDetail(String detail) {
    this.detail = detail;
  }

  public Error debugging(String debugging) {
    this.debugging = debugging;
    return this;
  }

   /**
   * Debugging information for DEV and QA environments.
   * @return debugging
  **/
  @Schema(description = "Debugging information for DEV and QA environments.")
  public String getDebugging() {
    return debugging;
  }

  public void setDebugging(String debugging) {
    this.debugging = debugging;
  }

  public Error invalidParams(List<ErrorInvalidparams> invalidParams) {
    this.invalidParams = invalidParams;
    return this;
  }

  public Error addInvalidParamsItem(ErrorInvalidparams invalidParamsItem) {
    if (this.invalidParams == null) {
      this.invalidParams = new ArrayList<ErrorInvalidparams>();
    }
    this.invalidParams.add(invalidParamsItem);
    return this;
  }

   /**
   * An array of validation errors.
   * @return invalidParams
  **/
  @Schema(description = "An array of validation errors.")
  public List<ErrorInvalidparams> getInvalidParams() {
    return invalidParams;
  }

  public void setInvalidParams(List<ErrorInvalidparams> invalidParams) {
    this.invalidParams = invalidParams;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.type, error.type) &&
        Objects.equals(this.title, error.title) &&
        Objects.equals(this.status, error.status) &&
        Objects.equals(this.instance, error.instance) &&
        Objects.equals(this.detail, error.detail) &&
        Objects.equals(this.debugging, error.debugging) &&
        Objects.equals(this.invalidParams, error.invalidParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, title, status, instance, detail, debugging, invalidParams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    instance: ").append(toIndentedString(instance)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    debugging: ").append(toIndentedString(debugging)).append("\n");
    sb.append("    invalidParams: ").append(toIndentedString(invalidParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
