/*
 * Energy Scoring
 * Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SiteMetadata
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-09-22T12:58:44.587342+02:00[Europe/Madrid]")
public class SiteMetadata {
  @SerializedName("grossArea")
  private Integer grossArea = null;

  @SerializedName("buildingOccupants")
  private Integer buildingOccupants = null;

  @SerializedName("daysPerWeekWithVisitors")
  private Integer daysPerWeekWithVisitors = null;

  @SerializedName("numberOfVisitorsPerDay")
  private Integer numberOfVisitorsPerDay = null;

  @SerializedName("visitDuration")
  private Double visitDuration = null;

  @SerializedName("weeklyOperatingHours")
  private Integer weeklyOperatingHours = null;

  public SiteMetadata grossArea(Integer grossArea) {
    this.grossArea = grossArea;
    return this;
  }

   /**
   * Get grossArea
   * @return grossArea
  **/
  @Schema(example = "425", description = "")
  public Integer getGrossArea() {
    return grossArea;
  }

  public void setGrossArea(Integer grossArea) {
    this.grossArea = grossArea;
  }

  public SiteMetadata buildingOccupants(Integer buildingOccupants) {
    this.buildingOccupants = buildingOccupants;
    return this;
  }

   /**
   * Get buildingOccupants
   * @return buildingOccupants
  **/
  @Schema(example = "49", description = "")
  public Integer getBuildingOccupants() {
    return buildingOccupants;
  }

  public void setBuildingOccupants(Integer buildingOccupants) {
    this.buildingOccupants = buildingOccupants;
  }

  public SiteMetadata daysPerWeekWithVisitors(Integer daysPerWeekWithVisitors) {
    this.daysPerWeekWithVisitors = daysPerWeekWithVisitors;
    return this;
  }

   /**
   * Get daysPerWeekWithVisitors
   * @return daysPerWeekWithVisitors
  **/
  @Schema(example = "7", description = "")
  public Integer getDaysPerWeekWithVisitors() {
    return daysPerWeekWithVisitors;
  }

  public void setDaysPerWeekWithVisitors(Integer daysPerWeekWithVisitors) {
    this.daysPerWeekWithVisitors = daysPerWeekWithVisitors;
  }

  public SiteMetadata numberOfVisitorsPerDay(Integer numberOfVisitorsPerDay) {
    this.numberOfVisitorsPerDay = numberOfVisitorsPerDay;
    return this;
  }

   /**
   * Get numberOfVisitorsPerDay
   * @return numberOfVisitorsPerDay
  **/
  @Schema(example = "548", description = "")
  public Integer getNumberOfVisitorsPerDay() {
    return numberOfVisitorsPerDay;
  }

  public void setNumberOfVisitorsPerDay(Integer numberOfVisitorsPerDay) {
    this.numberOfVisitorsPerDay = numberOfVisitorsPerDay;
  }

  public SiteMetadata visitDuration(Double visitDuration) {
    this.visitDuration = visitDuration;
    return this;
  }

   /**
   * Get visitDuration
   * @return visitDuration
  **/
  @Schema(example = "0.0208", description = "")
  public Double getVisitDuration() {
    return visitDuration;
  }

  public void setVisitDuration(Double visitDuration) {
    this.visitDuration = visitDuration;
  }

  public SiteMetadata weeklyOperatingHours(Integer weeklyOperatingHours) {
    this.weeklyOperatingHours = weeklyOperatingHours;
    return this;
  }

   /**
   * Get weeklyOperatingHours
   * @return weeklyOperatingHours
  **/
  @Schema(example = "168", description = "")
  public Integer getWeeklyOperatingHours() {
    return weeklyOperatingHours;
  }

  public void setWeeklyOperatingHours(Integer weeklyOperatingHours) {
    this.weeklyOperatingHours = weeklyOperatingHours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SiteMetadata siteMetadata = (SiteMetadata) o;
    return Objects.equals(this.grossArea, siteMetadata.grossArea) &&
        Objects.equals(this.buildingOccupants, siteMetadata.buildingOccupants) &&
        Objects.equals(this.daysPerWeekWithVisitors, siteMetadata.daysPerWeekWithVisitors) &&
        Objects.equals(this.numberOfVisitorsPerDay, siteMetadata.numberOfVisitorsPerDay) &&
        Objects.equals(this.visitDuration, siteMetadata.visitDuration) &&
        Objects.equals(this.weeklyOperatingHours, siteMetadata.weeklyOperatingHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grossArea, buildingOccupants, daysPerWeekWithVisitors, numberOfVisitorsPerDay, visitDuration, weeklyOperatingHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SiteMetadata {\n");
    
    sb.append("    grossArea: ").append(toIndentedString(grossArea)).append("\n");
    sb.append("    buildingOccupants: ").append(toIndentedString(buildingOccupants)).append("\n");
    sb.append("    daysPerWeekWithVisitors: ").append(toIndentedString(daysPerWeekWithVisitors)).append("\n");
    sb.append("    numberOfVisitorsPerDay: ").append(toIndentedString(numberOfVisitorsPerDay)).append("\n");
    sb.append("    visitDuration: ").append(toIndentedString(visitDuration)).append("\n");
    sb.append("    weeklyOperatingHours: ").append(toIndentedString(weeklyOperatingHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
