# coding: utf-8

"""
    Energy Scoring

    Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_invalidparams import ErrorInvalidparams  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorInvalidparams(unittest.TestCase):
    """ErrorInvalidparams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorInvalidparams(self):
        """Test ErrorInvalidparams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_invalidparams.ErrorInvalidparams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
