# coding: utf-8

"""
    Energy Scoring

    Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.energy_performance_api import EnergyPerformanceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEnergyPerformanceApi(unittest.TestCase):
    """EnergyPerformanceApi unit test stubs"""

    def setUp(self):
        self.api = EnergyPerformanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_certification_scores(self):
        """Test case for create_certification_scores

        Creates Certification Score resources  # noqa: E501
        """
        pass

    def test_create_energy_certification(self):
        """Test case for create_energy_certification

        Creates an Certification Provider resource  # noqa: E501
        """
        pass

    def test_list_metrics(self):
        """Test case for list_metrics

        List all Metrics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
