/*
 * Energy Scoring
 * Schneider Electric provides OpenESX Energy Scoring API for its customer to integrate EcoStruxure services with their own Energy Scoring Provider of choice in order to evaluate buildings energy consumption and provide scores
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CertificationProvider;
import io.swagger.client.model.CertificationScore;
import io.swagger.client.model.Error;
import org.threeten.bp.OffsetDateTime;
import io.swagger.client.model.Timeserie;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for EnergyPerformanceApi
 */
@Ignore
public class EnergyPerformanceApiTest {

    private final EnergyPerformanceApi api = new EnergyPerformanceApi();

    /**
     * Creates Certification Score resources
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCertificationScoresTest() throws Exception {
        String siteId = null;
        List<CertificationScore> body = null;
        List<CertificationScore> response = api.createCertificationScores(siteId, body);

        // TODO: test validations
    }
    /**
     * Creates an Certification Provider resource
     *
     * Creates an Certification resource, to associate a site to an Certification Scoring Provider
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createEnergyCertificationTest() throws Exception {
        String siteId = null;
        CertificationProvider body = null;
        CertificationProvider response = api.createEnergyCertification(siteId, body);

        // TODO: test validations
    }
    /**
     * List all Metrics
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listMetricsTest() throws Exception {
        String siteId = null;
        OffsetDateTime updatedAtGte = null;
        OffsetDateTime updatedAtLt = null;
        List<Timeserie> response = api.listMetrics(siteId, updatedAtGte, updatedAtLt);

        // TODO: test validations
    }
}
